# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# --- Dockerfile for MCP Server iOS Simulator ---
FROM node:lts-alpine AS builder

# Create app directory
WORKDIR /app

# Copy package manifests and tsconfig
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies (skip scripts) and devDependencies for build
RUN npm install --ignore-scripts

# Copy source files
COPY src ./src

# Build the TypeScript project
RUN npm run build

# --- Final image ---
FROM node:lts-alpine
WORKDIR /app

# Copy built assets and production dependencies
COPY package.json package-lock.json ./
# Install only production dependencies
RUN npm install --production --ignore-scripts

# Copy dist directory from builder
COPY --from=builder /app/dist ./dist

# Create logs directory
RUN mkdir -p logs

# Command to run
ENTRYPOINT ["node", "dist/index.js"]
